### ISSUE TITLE
Kotlin Multiplatform

### ISSUE THREAD

**Issue by vanniktech** [JakeWharton/crossword#4]
Would be needed for https://github.com/JakeWharton/picnic/issues/8

**Comment by JakeWharton** [comment]
Yeah let's do it.

**Comment by JakeWharton** [comment]
Would be dramatically easier with https://youtrack.jetbrains.com/issue/KT-23251

**Comment by JakeWharton** [comment]
Feel free to test (the snapshot) if you can. Still want to add a suite of robust testing for my custom codepoint code which is likely not perfect yet.

**Comment by JakeWharton** [comment]
Also probably going to fix #2 first.

**Comment by vanniktech** [comment]
Snapshot works for me.
